name: tobeto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter_bloc: ^8.1.6
  glowy_borders: ^1.0.2
  curved_navigation_bar: ^1.0.6
  page_transition: ^2.1.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  intl_phone_field2: ^3.3.4
  gradient_borders: ^1.0.1
  carousel_slider: ^4.2.1
  chewie: ^1.8.1
  video_player: ^2.8.7
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  table_calendar: ^3.1.1
  flutter_slidable: ^3.1.0
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  webview_flutter: ^4.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/files/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
  class_name: Assets
