name: tobeto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter_bloc: ^8.1.5
  glowy_borders: ^1.0.2
  curved_navigation_bar: ^1.0.3
  page_transition: ^2.1.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  file_picker: ^8.0.3
  image_picker: ^1.1.1
  intl_phone_field2: ^3.3.4
  gradient_borders: ^1.0.0
  carousel_slider: ^4.2.1
  chewie: ^1.8.1
  video_player: ^2.8.6
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/files/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
  class_name: Assets
