name: tobeto
description: "Mobile app for Tobeto platform."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  internet_connection_checker_plus: ^2.5.2
  flutter_bloc: ^8.1.6 #state management
  hydrated_bloc: ^9.1.5 #caching with state management
  curved_navigation_bar: ^1.0.6 #bottom nav bar for platform screens
  page_transition: ^2.1.0 #navigation animation
  intl: any #intl:)
  file_picker: ^8.1.2
  image_picker: ^1.1.2 #file picker for various reasons
  intl_phone_field2: ^3.3.4 #used to format phonefiels
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  video_player: ^2.9.1 #video player
  url_launcher: ^6.3.0 #url launcher
  google_sign_in: ^6.2.1 #google sign in
  table_calendar: ^3.1.2
  flutter_slidable: ^3.1.1 #slideable
  introduction_screen: ^3.1.14 #onboarding
  uuid: ^4.5.1
  webview_flutter: ^4.9.0
  animated_toggle_switch: ^0.8.3
  country_flags: ^3.0.0 #country flags
  path_provider: ^2.1.4
  panara_dialogs: ^0.1.5 #dialog package
  gradient_borders: ^1.0.1 #border package
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/files/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
